prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix owl: <http://www.w3.org/2002/07/owl#>


select ?o where {
<http://dbpedia.org/resource/Landscaping> owl:sameAs ?o.
  FILTER regex(?o, "wikidata.org/entity") 

}
